### ISSUE TITLE
ImportError: No module named cv2

### ISSUE THREAD

**Issue by vedranius** [akmamun/live-stream-face-detection#2]
Hi,
I get this error when I try to run the **"app.py"**
Any way to solve this?
```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from camera import camera_stream
  File "/root/livestreamrecognition/live-stream-face-detection/camera.py", line 1, in <module>
    import cv2
ImportError: No module named cv2

```
Thanks!

**Comment by vedranius** [comment]
Solved by running:
`sudo apt install python-opencv` on Raspberry Pi
